# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu-back" do |vm_config| # Add a name to your VM here
    vm_config.vm.box = "ubuntu/bionic64"
    vm_config.vm.network "private_network", ip: "192.168.56.15"
    vm_config.vm.hostname = "back"
    vm_config.vm.synced_folder "../vm_keys", "/vagrant"
    vm_config.vm.provider "virtualbox" do |vb|
      vb.memory = "1028"
      vb.cpus = "1"
    end
    config.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "playbook.yml"
    end
  end
  

end
