---
- name: Install and Configure MongoDB
  hosts: all 
  become: yes           

  tasks:
    - name: Install pre requirements
      apt:
        name: 
          - gnupg
        state: present
      become: yes

    - name: Add MongoDB repository key
      apt_key:
        url: https://pgp.mongodb.com/server-7.0.asc 
        keyring: /usr/share/keyrings/mongodb-server-7.0.gpg
        state: present
      become: yes

    - name: Add MongoDB APT repository
      apt_repository:
        repo: deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/7.0 multiverse
        state: present
      become: yes

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present
        update_cache: yes
      become: yes

    - name: Start and enable MongoDB
      service:
        name: mongod
        state: started
        enabled: yes
      become: yes

    - name: Create an openssh keypair
      become_user: vagrant
      openssh_keypair:
        path: /home/vagrant/.ssh/id_rsa
        size: 2048

    - name: Copy SSH public key
      command: cp /home/vagrant/.ssh/id_rsa.pub /vagrant/{{ansible_hostname}}.pub
